// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getWorkingDirectory
CharacterVector getWorkingDirectory();
RcppExport SEXP _parsparse_getWorkingDirectory() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getWorkingDirectory());
    return rcpp_result_gen;
END_RCPP
}
// readSparseMatrix
SEXP readSparseMatrix(std::string filepath, std::string rep);
RcppExport SEXP _parsparse_readSparseMatrix(SEXP filepathSEXP, SEXP repSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filepath(filepathSEXP);
    Rcpp::traits::input_parameter< std::string >::type rep(repSEXP);
    rcpp_result_gen = Rcpp::wrap(readSparseMatrix(filepath, rep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parsparse_getWorkingDirectory", (DL_FUNC) &_parsparse_getWorkingDirectory, 0},
    {"_parsparse_readSparseMatrix", (DL_FUNC) &_parsparse_readSparseMatrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_parsparse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
