// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getWorkingDirectory
CharacterVector getWorkingDirectory();
RcppExport SEXP _parsparse_getWorkingDirectory() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getWorkingDirectory());
    return rcpp_result_gen;
END_RCPP
}
// readCooFromMtx
SEXP readCooFromMtx(std::string filepath);
RcppExport SEXP _parsparse_readCooFromMtx(SEXP filepathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filepath(filepathSEXP);
    rcpp_result_gen = Rcpp::wrap(readCooFromMtx(filepath));
    return rcpp_result_gen;
END_RCPP
}
// readSvtFromMtx
SEXP readSvtFromMtx(std::string filepath);
RcppExport SEXP _parsparse_readSvtFromMtx(SEXP filepathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filepath(filepathSEXP);
    rcpp_result_gen = Rcpp::wrap(readSvtFromMtx(filepath));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parsparse_getWorkingDirectory", (DL_FUNC) &_parsparse_getWorkingDirectory, 0},
    {"_parsparse_readCooFromMtx", (DL_FUNC) &_parsparse_readCooFromMtx, 1},
    {"_parsparse_readSvtFromMtx", (DL_FUNC) &_parsparse_readSvtFromMtx, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_parsparse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
