# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWorkingDirectory <- function() {
    .Call(`_parsparse_getWorkingDirectory`)
}

readCooFromMtx <- function(filepath) {
    .Call(`_parsparse_readCooFromMtx`, filepath)
}

readSvtFromMtx <- function(filepath) {
    .Call(`_parsparse_readSvtFromMtx`, filepath)
}

